package com.gm.mybatisTest.entity;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_number
     *
     * @mbg.generated
     */
    private String studentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_name
     *
     * @mbg.generated
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_class
     *
     * @mbg.generated
     */
    private String studentClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.chinese_score
     *
     * @mbg.generated
     */
    private Double chineseScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.math_score
     *
     * @mbg.generated
     */
    private Double mathScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.english_score
     *
     * @mbg.generated
     */
    private Double englishScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_number
     *
     * @return the value of student.student_number
     *
     * @mbg.generated
     */
    public String getStudentNumber() {
        return studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_number
     *
     * @param studentNumber the value for student.student_number
     *
     * @mbg.generated
     */
    public void setStudentNumber(String studentNumber) {
        this.studentNumber = studentNumber == null ? null : studentNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_name
     *
     * @return the value of student.student_name
     *
     * @mbg.generated
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_name
     *
     * @param studentName the value for student.student_name
     *
     * @mbg.generated
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_class
     *
     * @return the value of student.student_class
     *
     * @mbg.generated
     */
    public String getStudentClass() {
        return studentClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_class
     *
     * @param studentClass the value for student.student_class
     *
     * @mbg.generated
     */
    public void setStudentClass(String studentClass) {
        this.studentClass = studentClass == null ? null : studentClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.chinese_score
     *
     * @return the value of student.chinese_score
     *
     * @mbg.generated
     */
    public Double getChineseScore() {
        return chineseScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.chinese_score
     *
     * @param chineseScore the value for student.chinese_score
     *
     * @mbg.generated
     */
    public void setChineseScore(Double chineseScore) {
        this.chineseScore = chineseScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.math_score
     *
     * @return the value of student.math_score
     *
     * @mbg.generated
     */
    public Double getMathScore() {
        return mathScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.math_score
     *
     * @param mathScore the value for student.math_score
     *
     * @mbg.generated
     */
    public void setMathScore(Double mathScore) {
        this.mathScore = mathScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.english_score
     *
     * @return the value of student.english_score
     *
     * @mbg.generated
     */
    public Double getEnglishScore() {
        return englishScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.english_score
     *
     * @param englishScore the value for student.english_score
     *
     * @mbg.generated
     */
    public void setEnglishScore(Double englishScore) {
        this.englishScore = englishScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.user_name
     *
     * @return the value of student.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.user_name
     *
     * @param userName the value for student.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.password
     *
     * @return the value of student.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.password
     *
     * @param password the value for student.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}